return function()
    return {
        workspace.Towers.ToNI.Obby:GetChildren()[10],
        workspace.Towers.ToNI.Obby:GetChildren()[15],
        workspace.Towers.ToNI.Obby:GetChildren()[27],
        workspace.Towers.ToNI.Obby:GetChildren()[33],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[8]:GetChildren()[2],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[6]:GetChildren()[2],
        workspace.Towers.ToNI.Obby:GetChildren()[35],
        workspace.ClientParts["Kill Bricks"]:GetChildren()[7],
        workspace.ClientParts["Kill Bricks"]:GetChildren()[8],
        workspace.Towers.ToNI.Obby:GetChildren()[40],
        workspace.Towers.ToNI.Obby:GetChildren()[41],
        workspace.Towers.ToNI.Obby:GetChildren()[45],
        workspace.Towers.ToNI.Obby:GetChildren()[59],
        workspace.Towers.ToNI.Obby:GetChildren()[55],
        workspace.ClientParts.DistanceAnchoringObjects.Spinner.Part,
        workspace.Towers.ToNI.Obby:GetChildren()[8],
        workspace.Towers.ToNI.Obby:GetChildren()[95],
        workspace.Towers.ToNI.Obby:GetChildren()[101],
        workspace.Towers.ToNI.Obby:GetChildren()[104],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[10]:GetChildren()[2],
        workspace.Towers.ToNI.Obby:GetChildren()[87],
        workspace.Towers.ToNI.Obby:GetChildren()[91],
        workspace.Towers.ToNI.Obby:GetChildren()[92], --F2
        workspace.Towers.ToNI.Obby:GetChildren()[90],
        workspace.Towers.ToNI.Obby:GetChildren()[106],
        workspace.Towers.ToNI.Obby:GetChildren()[105],
        workspace.Towers.ToNI.Obby:GetChildren()[109],
        workspace.Towers.ToNI.Obby:GetChildren()[112],
        workspace.Towers.ToNI.Obby:GetChildren()[122],
        workspace.Towers.ToNI.Obby:GetChildren()[147],
        workspace.Towers.ToNI.Obby:GetChildren()[149],
        workspace.Towers.ToNI.Obby:GetChildren()[152],
        workspace.Towers.ToNI.Obby:GetChildren()[155],
        workspace.Towers.ToNI.Obby:GetChildren()[158],
        workspace.Towers.ToNI.Obby:GetChildren()[165],
        workspace.Towers.ToNI.Obby:GetChildren()[139],
        workspace.Towers.ToNI.Obby:GetChildren()[172],
        workspace.Towers.ToNI.Obby:GetChildren()[175],
        workspace.Towers.ToNI.Obby:GetChildren()[178],
        workspace.Towers.ToNI.Obby:GetChildren()[179],
        workspace.Towers.ToNI.Obby:GetChildren()[180],
        workspace.Towers.ToNI.Obby:GetChildren()[177],
        workspace.Towers.ToNI.Obby.Conveyor,
        workspace.Towers.ToNI.Obby:GetChildren()[184],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[16]:GetChildren()[2],
        workspace.Towers.ToNI.Obby:GetChildren()[191],
        workspace.Towers.ToNI.Obby:GetChildren()[185],
        workspace.Towers.ToNI.Obby:GetChildren()[115]
        
    
    }
end
